### ISSUE TITLE
Can not access feature properties in Openlayer3

### ISSUE THREAD

**Issue by bwyss** [spatialdev/PGRestAPI#126]
I am serving a vector tile from Chubbs and rendering it with Openlayers3.14.3. I am not able to access the feature properties of the vector tile.

My layer:

    var observationLayer = new ol.layer.VectorTile({
       source: new ol.source.VectorTile({
        format: new ol.format.MVT(),
        tileGrid: ol.tilegrid.createXYZ({maxZoom: 22}),
        tilePixelRatio: 16,
        url: '/services/postgis/test_observations/geometry/vector-tiles/{z}/{x}/{y}.pbf'
      }),
      style: observationStyle
    }); 

Trying to access feature properties:

       map.on(ol.MapBrowserEvent.EventType.SINGLECLICK, function (e) {
        console.log('e:');
        console.log(e);
        map.forEachFeatureAtPixel(e.pixel, function (feature, layer) {
          console.log('feature.getProperties():');
          console.log(feature.getProperties());
          // This only returns: id: "test_observations_geometry"
          // instead of all of the layers attributes. If I change the layer to a GeoJSON source,
          // then it works correctly. 
        });
      });

**Comment by apollolm** [comment]
By default, only the id is returned to cut down on the size of the payload/tile coming from the server.  I chose to only show id rather than show all properties.  You can add in the properties you'd like to have returned by adding a 'fields' querystring parameter to the end of the vector tile request URL, and using a comma separated list of your field names.
 
    {z}/{x}/{y}.pbf?fields=myfield1,myfield2,myfield3

I don't think this is documented (sorry).

**Comment by bwyss** [comment]
WOW works!!! Thank you
